### PR TITLE
fix issue 87

### PR DESCRIPTION
**Pull request by shadow1163**
### Types of changes
_Put an `x` in the boxes that apply_

- [* ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### How has this been tested?
I updated app.py file, and test pass on my local environment.

### CODE REVIEW

**Comment by JoeSSS** [comment]
Fixes #87

**Comment by butomo1989** [comment]
Hi @shadow1163 @JoeSSS , 

why we need this PR? does #96 not fix the issue that you have?

**Comment by JoeSSS** [comment]
I think that @shadow1163 has different issue than I have. I would use @red-avtovo help here, as he created this code in the first place.

**Comment by JoeSSS** [comment]
Or just let line 53 as it was and then assign `is_first_run = not is_initialized()` this will be more readable. But overall nice catch!

**Pull request closed without merging**
