### PR TITLE
Support for Android 8.0 and 8.1

### LINKED ISSUE #24: Support android 8.0.0 (API 26) and 8.1.0 (API 27)

### PR DESCRIPTION
**Pull request by JoeSSS**
### Purpose of changes
This PR adds support for Android 8.0 (API 26)

### Types of changes
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### How has this been tested?
Run docker, checked that emulator is healthy in VNC + ran Espresso + Calabash tests against port-forwarded ADB.

Fixes #24

### CODE REVIEW

**Comment by JoeSSS** [comment]
@butomo1989 I'm not sure if this can go to master (as it will most likely break other API lvls) but this is what made it work for me + it will use ranchu kernel which appeared to be more performant. I gonna test this PR again tomorrow when I have access to the environment

**Comment by butomo1989** [comment]
Hi @JoeSSS , 

Thanks a lot for the PR. 

The hint:
you do not need to change the Android version and API_LEVEL on the Dockerfile but you need to add the version on the release.sh and you can run `./release.sh build` and it will ask all the parameters that you need to give. After it is built successfully, you can check if that image works or not. 

Let me know if you need some help, I can help you so we can merge this PR to master branch.

**Comment by JoeSSS** [comment]
Hi @butomo1989 , 

Yeah, I see. Yesterday I created a PR from the iPad, so it wasn't so easy to navigate through the project. I will continue on it, as we already used it and the performance improved a lot :) (frame drop on the current setup is above 90%, and with this one it is ~40% which is actually better than on my MacBook)

**Comment by JoeSSS** [comment]
thank you for this repo :) it simplified a lot for us) 
We're using the emulator quite extensive (~140 simultaneous emulators run on our CI through the day). So performance is very important for us and I spent last 2 weeks trying to improve stability and found out a lot of interesting stuff. For example, x86_64 architecture don't run very stable.. the crush I reported in #82 disappear by using x86 architecture. Not sure how you feel about this (as x64 should obviously be better) but I'm gonna use x86 images for our project.

**Comment by red-avtovo** [comment]
I made a check for Android 5 (API 21) with the lates emulator, which is @JoeSSS using here. It just works. So that definitely worth to merge it

**Comment by butomo1989** [comment]
Hi.

Thank you @red-avtovo for the check. @JoeSSS do you still work on this branch (e.g. work on release.sh script) or is it finished? I can also continue to modify release.sh.

**Comment by JoeSSS** [comment]
I will continue (hopefully today). Do you want me to change the architecture to x86 also? I see that this works better and also API 27 doesn't have x86_64 image at all

**Comment by red-avtovo** [comment]
This PR is getting more and more looks like #72 
I think we should finish here and merge it

**Comment by JoeSSS** [comment]
Whatever works better. We should finish with both ;)
I'm testing my PR now.

**Comment by JoeSSS** [comment]
Tested on Android: 8.0, 8.1, 7.0. All 3 versions work fluent.

**Comment by butomo1989** [comment]
Hi @JoeSSS @red-avtovo , 

Thanks a lot for your contributions! I will release the new version after I merge PR #83

**Pull request merged**
