### PR TITLE
Add Cloud instructions for GCE

### PR DESCRIPTION
**Pull request by kjlubick**
### Purpose of changes
I got the container to run on GCE and want to share how.

### How has this been tested?
Created a GCE instance following the linked instructions and ran the container there.

### CODE REVIEW

**Comment by kjlubick** [comment]
You mean, like a mini-tutorial how to spin up a GCE instance with the emulator?  Sure, but it may take a little bit.

**Comment by butomo1989** [comment]
yes, a mini tutorial would be great. but you can also add deployment template, e.g. if you use kubernetes or something to deploy docker-android on GCE, you can also add that deployment template file as well. @kjlubick 

Thanks a lot! so let me know if you prefer to do it in different PR.

**Comment by kjlubick** [comment]
Hmm, I don't use Kubernetes or anything, running the emulator is more or less a one-shot thing.  I'll add the mini tutorial later today.

**Comment by kjlubick** [comment]
Done - there's really not much to add on top of the documentation at cloud.google.com other than the little recipe I used for installing an apk.

**Pull request merged**
