### PR TITLE
Build docker images with play store

### PR DESCRIPTION
**Pull request by greenerchen**
### Purpose of changes
Add logic to build docker images with play store for emulators with x86 processor and API 24 or later version

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Support new platform/sdk/system images/devices

### How has this been tested?
Not yet done
running release.sh to build docker images locally

### CODE REVIEW

**Comment by butomo1989** [comment]
Hi @greenerchen , 

Thank you for the PR! you help me a lot with your contributions in this project! :) but sorry, I will check this PR next week and continue to help you with it.

**Comment by butomo1989** [comment]
Hi @greenerchen , 

sorry, I still do not have time to review this PR. but last time I tried I have some issue with android 8.0 and 8.1 and also some devices issue with x86. :(  It would be great if you build locally, test it and give me feedback.

**Comment by tg44** [comment]
git cloned, then a 8.1 image builded. The emulator starts and then exists.

```
root@480b50d9516d:~# ./src/appium.sh
[205] [ INFO] app - Android version: 8.1
API level: 27
Processor: x86
System image: x86
Image type: google_apis_playstore
[205] [ INFO] app - Device: Nexus S
[205] [ INFO] app - AVD name: nexus_s_8.1
[205] [ INFO] app - Preparing emulator...
[205] [ INFO] app - Command to create avd: avdmanager create avd -f -n nexus_s_8.1 -b google_apis_playstore/x86 -k "system-images;android-27;google_apis_playstore;x86" -d Nexus\ S -p/root/android_emulator
[205] [ INFO] app - Skin was added in config.ini
[205] [ INFO] app - Run emulator...
emulator: ERROR: This AVD's configuration is missing a kernel file! Please ensure the file "kernel-qemu" is in the same location as your system image.
emulator: ERROR: ANDROID_SDK_ROOT is undefined
root@480b50d9516d:~#
```

**Comment by JoeSSS** [comment]
Missing kernel can be fixed by something like #81 Using the emulator executable itself will pick the ranchu and correct kernel for linux.

**Comment by red-avtovo** [comment]
Yeah, this PR is 100% correct but emulator, that you are using. I built an image with Androi 8.0 with Playstore preinstalled and it works like a charm

**Comment by butomo1989** [comment]
Hi @greenerchen , 

Could you fix the conflict? so I can merge it.

**Comment by butomo1989** [comment]
Thanks a lot @greenerchen for the PR!

**Pull request merged**
