### PR TITLE
Use latest version of chromedriver

### PR DESCRIPTION
**Pull request by bonigarcia**
### Purpose of changes
Update the version of [chromedriver](http://chromedriver.chromium.org/downloads) in order to use latest version of Chrome in the Android device through an Appium client.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### How has this been tested?
When using Chrome as browser in the latest version of Docker images through an Appium client, I get the following error:

`An unknown server-side error occurred while processing the command. (Original error: unknown error: Chrome version must be >= 53.0.2785.0)`

This is due to an incompatibility between Chrome and chromedriver. This should be fixed by upgrading the version of chromedriver.

### CODE REVIEW

**Comment by bonigarcia** [comment]
@red-avtovo Even better that parameterizing the version, I have just changed the script to find out automatically the [latest version of chromedriver](https://chromedriver.storage.googleapis.com/LATEST_RELEASE) and download it.

**Comment by diemol** [comment]
I agree with @red-avtovo, because the ChromeDriver version depends on what Chrome apk is installed in the emulator, and using the latest ChromeDriver won't work out of the box for many Android versions.

If a user has an updated Chrome apk, it means that s/he was able to install it after the emulator started and then s/he could also adjust the ChromeDriver version.

Overall, I also think than using arguments is a better solution.

**Comment by bonigarcia** [comment]
Then the question is: Which is version of Chrome installed in the Android devices? Because if that version is fixed, there is not need of a parameter but a 1-1 relationship between the Android version (7.0 and 7.1.1 at this time) and its corresponding chromedriver version.

Another related question is... Why is Chrome not available on old Android versions (5.0.1, 5.1.1, 6.0)? I read that [Chrome is available for Android since version 4](https://androidandme.com/2012/02/applications/goodbye-old-browser-chrome-to-become-the-standard-browser-on-android-4-0-and-above/). For web testing through Appium, ideally, it would be desirable to have the chance to chose between default Android browser (`com.android.browser`) and Chrome (`com.android.chrome`). Is not possible to install both browsers in all Android devices?

**Comment by butomo1989** [comment]
Hi @bonigarcia ,

the default version of Chrome app for each android version is different, for example for the current Android version 7.1.1, it uses version 55.0.xx and for version 8.1, it uses version 61.0.xxx. But I think you can update the chrome version inside Emulator manually.
chrome version

I agree with @red-avtovo and @diemol that it would be great if we get the version of the chrome driver in release.sh and pass as environment variable to Dockerfile so we do not need to change the Dockerfile every time we modify the version. what do you think? I can also do it if you want.

Regarding Android version <= 6.0, the system image do not provide Google related application as I remembered, you can still have Chrome app under that version but you need to install it manually. 
But I think you do not need which Android version is running if you do browser testing. you just need to know which device ir running, isnt it?

**Comment by butomo1989** [comment]
I will merge it for now, because I need to modify release.sh a lot for travis build. Thank you @bonigarcia for the PR!

**Comment by fr34kyn01535** [comment]
The change is not yet in the public image, it is?

**Pull request merged**
